# Generated by Django 5.1.3 on 2024-11-19 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caremi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="last_activity",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 19, 9, 5, 43, 432633, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
