# Generated by Django 5.1.3 on 2024-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caremi", "0005_voucher_uservoucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="code",
            field=models.CharField(default="GOGREEN", max_length=10),
        ),
    ]
